#!/usr/bin/env python3
"""Scan runs/ directory and generate registry.toml.

Usage: python scripts/aggregate.py --data-dir ./ --output registry.toml
"""

import argparse, sys, tomllib
from pathlib import Path
from datetime import datetime, timezone

def find_runs(data_dir: Path) -> list[dict]:
    """Find all run directories under runs/{game}/{agent}/{run_id}/."""
    runs = []
    runs_root = data_dir / "runs"
    if not runs_root.is_dir():
        return runs
    for game_dir in sorted(runs_root.iterdir()):
        if not game_dir.is_dir(): continue
        for agent_dir in sorted(game_dir.iterdir()):
            if not agent_dir.is_dir(): continue
            for run_dir in sorted(agent_dir.iterdir()):
                if not run_dir.is_dir(): continue
                run_toml = run_dir / "run.toml"
                summary_json = run_dir / "summary.json"
                if not run_toml.exists():
                    continue
                try:
                    meta = tomllib.loads(run_toml.read_text())
                except Exception:
                    meta = {}
                summary = {}
                if summary_json.exists():
                    import json
                    try:
                        summary = json.loads(summary_json.read_text())
                    except Exception:
                        pass
                runs.append({
                    "run_id": run_dir.name,
                    "game": game_dir.name,
                    "agent": agent_dir.name,
                    "type": meta.get("type", "eval"),
                    "path": str(run_dir.relative_to(data_dir)),
                    "created": meta.get("created", ""),
                    "git_commit": meta.get("git_commit", ""),
                    "summary": {
                        "best_elo": summary.get("best_elo"),
                        "final_elo": summary.get("final_elo"),
                        "wall_hours": summary.get("wall_hours"),
                        "total_steps": summary.get("total_steps"),
                        "win_rate": summary.get("win_rate"),
                    },
                })
    return runs

def main():
    p = argparse.ArgumentParser(description="Generate registry.toml from runs/")
    p.add_argument("--data-dir", default=".")
    p.add_argument("--output", default="registry.toml")
    args = p.parse_args()
    data_dir = Path(args.data_dir)
    runs = find_runs(data_dir)
    # Generate TOML
    lines = ["# Auto-generated by aggregate.py — do not edit manually", ""]
    for r in runs:
        lines.append("[[runs]]")
        lines.append(f'run_id = "{r["run_id"]}"')
        lines.append(f'game = "{r["game"]}"')
        lines.append(f'agent = "{r["agent"]}"')
        lines.append(f'type = "{r["type"]}"')
        lines.append(f'path = "{r["path"]}"')
        lines.append(f'created = "{r["created"]}"')
        lines.append(f'git_commit = "{r["git_commit"]}"')
        # Inline summary
        s = r["summary"]
        lines.append("[runs.summary]")
        for k, v in s.items():
            if v is not None:
                if isinstance(v, float):
                    lines.append(f'{k} = {v}')
                elif isinstance(v, int):
                    lines.append(f'{k} = {v}')
        lines.append("")
    out = Path(args.output)
    out.write_text("\n".join(lines))
    print(f"Wrote {len(runs)} runs to {out}", file=sys.stderr)

if __name__ == "__main__":
    main()
