#!/usr/bin/env python3
"""Scan runs/ directory and generate registry.toml.

Reads run.toml + summary.json from each run, writes registry.toml
for CI visualization.

Usage: python scripts/aggregate.py --data-dir ./ --output registry.toml
"""

import argparse, json, sys, tomllib
from pathlib import Path


def _get_meta_field(meta: dict, key: str, default=""):
    """Read a field from run.toml, handling both [run] section and flat formats."""
    if "run" in meta:
        return meta["run"].get(key, default)
    return meta.get(key, default)


def find_runs(data_dir: Path) -> list[dict]:
    runs = []
    runs_root = data_dir / "runs"
    if not runs_root.is_dir():
        return runs

    for game_dir in sorted(runs_root.iterdir()):
        if not game_dir.is_dir(): continue
        for agent_dir in sorted(game_dir.iterdir()):
            if not agent_dir.is_dir(): continue
            for run_dir in sorted(agent_dir.iterdir()):
                if not run_dir.is_dir(): continue
                run_toml = run_dir / "run.toml"
                if not run_toml.exists():
                    continue
                try:
                    raw = tomllib.loads(run_toml.read_text())
                except Exception:
                    raw = {}

                # summary.json is authoritative for metrics
                s = {}
                sj = run_dir / "summary.json"
                if sj.exists():
                    try:
                        s = json.loads(sj.read_text())
                    except Exception:
                        pass

                # Merge: summary.json fields override, fallback to run.toml
                runs.append({
                    "run_id": run_dir.name,
                    "game": game_dir.name,
                    "agent": agent_dir.name,
                    "type": s.get("run_type") or _get_meta_field(raw, "type", "eval"),
                    "path": str(run_dir.relative_to(data_dir)),
                    "created": s.get("created") or _get_meta_field(raw, "created", ""),
                    "git_commit": s.get("git_commit") or _get_meta_field(raw, "git_commit", ""),
                    "summary": {
                        "best_elo": s.get("best_elo"),
                        "final_elo": s.get("final_elo"),
                        "wall_hours": s.get("wall_hours"),
                        "total_steps": s.get("total_steps"),
                        "win_rate": s.get("win_rate"),
                    },
                })
    return runs


def _toml_val(v):
    if v is None: return ""
    if isinstance(v, bool): return str(v).lower()
    if isinstance(v, str): return f'"{v}"'
    if isinstance(v, float): return f"{v}"
    if isinstance(v, int): return f"{v}"
    return f'"{v}"'


def main():
    p = argparse.ArgumentParser(description="Generate registry.toml from runs/")
    p.add_argument("--data-dir", default=".")
    p.add_argument("--output", default="registry.toml")
    args = p.parse_args()
    data_dir = Path(args.data_dir)
    runs = find_runs(data_dir)

    lines = ["# Auto-generated by aggregate.py — do not edit manually", ""]
    for r in runs:
        lines.append("[[runs]]")
        lines.append(f'run_id = "{r["run_id"]}"')
        lines.append(f'game = "{r["game"]}"')
        lines.append(f'agent = "{r["agent"]}"')
        lines.append(f'type = "{r["type"]}"')
        lines.append(f'path = "{r["path"]}"')
        if r["created"]: lines.append(f'created = "{r["created"]}"')
        if r["git_commit"]: lines.append(f'git_commit = "{r["git_commit"]}"')
        # Summary as inline dict
        s = r["summary"]
        summary_items = []
        for k, v in s.items():
            if v is not None:
                summary_items.append(f'{k} = {_toml_val(v)}')
        if summary_items:
            lines.append("[runs.summary]")
            lines.extend(summary_items)
        lines.append("")

    out = Path(args.output)
    out.write_text("\n".join(lines))
    print(f"Wrote {len(runs)} runs to {out}", file=sys.stderr)


if __name__ == "__main__":
    main()
